### PR TITLE
updated dev.py

### PR DESCRIPTION
**Pull request by nicolehaug**
To include hostname http://ga-dev.fs2c.usda.gov

### CODE REVIEW

**Review by beechnut — DISMISSED** [review]
I'm having the thought that there might be a benefit to separating local dev and AWS dev settings into different files. That said, I'm not seeing any imminent issues; that's a decision we can always make later.

**Comment by nicolehaug** [comment]
@beechnut  i'm unable to see the failure details via circleci - are you able to see the failure and post details here for us? Thanks

**Review by nicolehaug — COMMENTED** [review]
updated potential syntax error

**Comment by beechnut** [comment]
> @beechnut i'm unable to see the failure details via circleci - are you able to see the failure and post details here for us? Thanks

This might not be you—there's a CircleCI partial outage reported, and I've been having trouble seeing results as well. There was a 502 Bad Gateway to start, and this latest build has been "preparing" for 2 minutes with no steps yet. I'll keep checking back in periodically to check if the results have truly finished.

**Review by nicolehaug — COMMENTED** [review]
updated syntax

**Review by nicolehaug — COMMENTED** [review]
syntax updates - http instead of https

**Comment by beechnut** [comment]
@nicolehaug Request: Would you combine the changes in #338 and #339 into one commit and open a new PR with just that commit? This request is partly motivated by errant CircleCI builds and partly by wanting to keep a relatively clean git history. Thanks!

**Comment by nicolehaug** [comment]
opening one pr with multiple requests including this one

**Pull request closed without merging**
